config:
  inputs: |
    [INPUT]
        Name             tail
        Tag              kube.*
        Path             /var/log/containers/*.log
        Skip_Long_Lines  On
        Skip_Empty_Lines On
        Mem_Buf_Limit    300MB
        Refresh_Interval 30
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On  
    [FILTER]
        Name modify
        Match *
        Rename log message
        Remove time
  outputs: |
    [OUTPUT]
        Name          forward
        Match         *
        Host          fluentd-aggregator
        Port          24224
