forwarder:
  enabled: false

aggregator:
  configMapFiles:
    fluentd-inputs.conf: |
      <source>
        @type forward
        bind 0.0.0.0
        port 24224
      </source>

      <source>
        @type http
        bind 0.0.0.0
        port 9880
      </source>

      <filter *.**>
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      emit_invalid_record_to_error false
      <parse>
        @type json
      </parse>
      </filter>
    fluentd-output.conf: |
      <match *.**>
      @type elasticsearch
      @log_level debug
      include_tag_key true
      host quickstart-7-es-http
      port 9200
      scheme https
      ssl_verify false
      logstash_format true
      logstash_prefix fluentd
      reload_connections false
      reconnect_on_error true
      reload_on_failure true
      request_timeout 15s
      flush_interval 10s
      user elastic
      password 3Z031hA4NfRe8K4SmS11CyS4
      default_elasticsearch_version 7
      <buffer>
        timekey 10s
        flush_thread_count 5
        flush_interval 10s
        chunk_limit_size 16m
        queue_limit_length 96
        flush_mode interval
        retry_max_interval 30
        retry_forever false
        flush_at_shutdown true
        </buffer>
      </match>
